// Offline worker for the installable Writing Playground. Generated by scripts/build.js; edit scripts/sw.template.js.
// Keeps a copy of every file the page needs, so the app opens without a connection. A new build changes
// VERSION, which makes the browser fetch the new files and drop the old copy.
const VERSION = '6eb0d4333a28';
const CACHE = `writing-playground-${VERSION}`;
const FONTS = 'writing-playground-fonts';
const FILES = [
  "./",
  "index.html",
  "css/app.css",
  "js/core/text.js",
  "js/core/lexicon.js",
  "js/core/checks.js",
  "js/core/diff.js",
  "js/genres/comedy.js",
  "js/genres/video.js",
  "js/genres/story.js",
  "js/genres/novel.js",
  "js/genres/essay.js",
  "js/genres/poetry.js",
  "js/genres/copy.js",
  "js/genres/speech.js",
  "js/genres/screenplay.js",
  "js/genres/drills.js",
  "js/genres/warmups.js",
  "js/genres/plans.js",
  "js/genres/readings.js",
  "js/ui/editor.js",
  "js/ui/coach.js",
  "js/app/core.js",
  "js/app/layout.js",
  "js/app/checks.js",
  "js/app/fixes.js",
  "js/app/ideas.js",
  "js/app/practice.js",
  "js/app/drafts.js",
  "js/app/frameworks.js",
  "js/app/guide.js",
  "js/app/reading.js",
  "js/app/sync.js",
  "js/app/install.js",
  "js/app/learn.js",
  "js/app/tools.js",
  "js/app.js",
  "manifest.webmanifest",
  "icons/icon.svg",
  "icons/icon-192.png",
  "icons/icon-512.png",
  "icons/maskable-512.png",
  "icons/apple-touch-icon.png"
];

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(FILES)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE && k !== FONTS).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  // Fonts: use the saved copy, refresh it in the background.
  if (url.hostname === 'fonts.googleapis.com' || url.hostname === 'fonts.gstatic.com') {
    e.respondWith(caches.open(FONTS).then(async (c) => {
      const hit = await c.match(req);
      const fresh = fetch(req).then((res) => {
        if (res.ok || res.type === 'opaque') c.put(req, res.clone());
        return res;
      }).catch(() => hit);
      return hit || fresh;
    }));
    return;
  }
  if (url.origin !== self.location.origin) return;
  // The app's own files: the saved copy for this version, else the network.
  e.respondWith(
    caches.match(req, { ignoreSearch: true }).then((hit) => hit || fetch(req).catch(() => (req.mode === 'navigate' ? caches.match('index.html') : Response.error()))),
  );
});
