/*
 * Practice drills: one rule at a time. Each drill opens a short flawed passage
 * as a new draft with its check spotlighted; the writer fixes it, then compares
 * with a model answer.
 *   rule: the check id the drill trains (always runs, even on short text)
 *   framework: optional framework to apply (poetry forms)
 */
(function (WP) {
  'use strict';

  WP.drills = {
    comedy: [
      {
        id: 'c-punch',
        title: 'Land the punch word last',
        rule: 'punch-last',
        task: 'Rewrite each joke so the surprising word is the very last thing the audience hears.',
        text: 'My doctor told me to watch my drinking. So now I drink in front of a mirror, I guess.\n\nI finally told my plants I love them. Three of them died that week, which was weird or something.',
        hint: 'Cut everything after the surprise. If the surprise is in the middle, rebuild the sentence around it.',
        model: 'My doctor told me to watch my drinking. So now I drink in front of a mirror.\n\nI finally told my plants I love them. Three of them died that week. Apparently love is a lot of pressure.',
      },
      {
        id: 'c-setup',
        title: 'Trim a bloated setup',
        rule: 'setup-economy',
        task: 'Cut this setup down to under 20 words without losing the joke.',
        text: 'So the other day, and this was a Tuesday I think, or maybe a Wednesday, it does not really matter, I decided that I was finally going to go to the gym that I have been paying for since January, which is a long time if you think about it, and when I got there the woman at the front desk asked for my name. She said I wasn’t in the system. I’ve been donating.',
        hint: 'A setup needs who, where and what’s wrong. Everything else is delay.',
        model: 'I finally went to the gym I’ve paid for since January. The front desk said I wasn’t in the system. So I’ve been donating.',
      },
      {
        id: 'c-three',
        title: 'Break the pattern on three',
        rule: 'rule-of-three',
        task: 'Cut the list to exactly three items, and make the third one break the pattern in a surprising way.',
        text: 'To get ready for my job interview I ironed my shirt, polished my shoes, printed my résumé, and practiced my handshake. I wanted them to see the real me.',
        hint: 'Two normal items set the pattern. The third keeps the same rhythm but comes from the wrong category.',
        model: 'To get ready for my job interview I ironed my shirt, polished my shoes, and Googled “how to have a personality.” I wanted them to see the real me.',
      },
      {
        id: 'c-specific',
        title: 'Make it specific',
        rule: 'specificity',
        task: 'Replace every vague word with a name, a brand, a number or a precise detail.',
        text: 'I went to a store late at night and bought some stuff, and a guy at the counter looked at me like I was a weird person. It was a whole thing.',
        hint: 'What store? What time? What exactly did you buy? Specific is funny.',
        model: 'I went to a 7-Eleven at 2 a.m. and bought a Slurpee and one single tomato, and the cashier looked at me like I’d just confessed to a crime.',
      },
    ],
    video: [
      {
        id: 'v-hook',
        title: 'Replace the greeting with a hook',
        rule: 'hook',
        task: 'Rewrite the opening so the first sentence makes the viewer need to keep watching. No greeting.',
        text: 'Hey everyone, welcome back to my channel! Today I am going to talk about how to wake up earlier in the morning.',
        hint: 'Try a bold claim, a question, a number, or a promise about the viewer.',
        model: 'You’re not lazy. Your alarm is in the wrong place. Here’s the 10-second fix that got me up at 6 a.m. every day this month.',
      },
      {
        id: 'v-speak',
        title: 'Make it speakable',
        rule: 'long-sentences',
        task: 'Split this into short sentences you could say out loud without running out of breath.',
        text: 'The reason most people fail when they try to learn guitar is that they start with songs that are far too hard for their current skill level and they get frustrated within the first two weeks and then they put the guitar in the closet where it stays for the next ten years collecting dust.',
        hint: 'One idea per sentence. Read it aloud and break where you breathe.',
        model: 'Most people quit guitar in two weeks. Why? They start with songs that are way too hard. They get frustrated. And the guitar goes in the closet for ten years.',
      },
      {
        id: 'v-but',
        title: 'And then → but / so',
        rule: 'but-therefore',
        task: 'Reconnect these beats with “but” and “so” so each one causes the next.',
        text: 'I wanted to run a marathon. And then I signed up for one. And then I started training. And then I hurt my knee. And then I switched to swimming. And then I finished the race anyway.',
        hint: 'Every beat should be a problem (“but”) or a consequence (“so”).',
        model: 'I wanted to run a marathon, so I signed up and started training. But three weeks in, I hurt my knee. So I switched to swimming to stay fit. And on race day, I finished anyway.',
      },
      {
        id: 'v-you',
        title: 'Talk to the viewer',
        rule: 'you-focus',
        task: 'Rewrite so the viewer, not you, is the subject of most sentences.',
        text: 'I have been using this budgeting method for two years. I love it because I save a lot of money. I check my spending every Sunday. I think it is the best method I have ever tried and I want to share it.',
        hint: 'Swap “I do X” for “you can do X” and “here’s what you get”.',
        model: 'You can save hundreds a month with one habit. Every Sunday, you check what you spent. That’s it. Here’s exactly how you set it up in ten minutes.',
      },
    ],
    story: [
      {
        id: 's-show',
        title: 'Show the emotion',
        rule: 'telling-emotion',
        task: 'Rewrite so the reader knows how each character feels without the emotion being named.',
        text: 'Sarah was very angry at her brother for reading her diary. Her brother felt guilty. Their mother was tired of the fighting.',
        hint: 'What do angry, guilty and tired people do with their hands, their voices, their eyes?',
        model: 'Sarah snatched the diary back so hard the cover tore. Her brother studied his shoes. From the kitchen, their mother called, “Not tonight,” without turning around.',
      },
      {
        id: 's-filter',
        title: 'Remove filter words',
        rule: 'filter-words',
        task: 'Cut “heard”, “saw”, “felt” and similar words so the reader experiences things directly.',
        text: 'She heard the door creak behind her. She saw a shadow move across the wall. She felt the cold air on her neck and realized someone was in the room.',
        hint: 'Describe the thing itself: not “she heard the door creak” but “the door creaked”.',
        model: 'Behind her, the door creaked. A shadow slid across the wall. Cold air touched the back of her neck. Someone was in the room.',
      },
      {
        id: 's-senses',
        title: 'Use three senses',
        rule: 'senses',
        task: 'Rewrite the description using at least three different senses.',
        text: 'The kitchen was old. There was a table and some chairs. My grandmother was cooking dinner. It was a nice place to be.',
        hint: 'What did it smell like? What sounds were there? What did things feel like to touch?',
        model: 'The kitchen smelled of garlic and burnt sugar. The radio hissed between stations while my grandmother stirred, her spoon clicking against the pot. The table was sticky under my elbows, and warm from the stove.',
      },
      {
        id: 's-tags',
        title: 'Fix the dialogue tags',
        rule: 'dialogue',
        task: 'Replace fancy tags and adverbs with “said”, or with an action beat.',
        text: '“Where were you?” she demanded angrily.\n“Out,” he retorted.\n“Out where?” she exclaimed loudly.\n“Just out,” he chuckled.',
        hint: 'Let the words carry the emotion. An action beat (“She folded her arms.”) can replace a tag entirely.',
        model: '“Where were you?” she said.\n“Out.”\n“Out where?” She folded her arms.\n“Just out.” He grinned and dropped his keys in the bowl.',
      },
    ],
    essay: [
      {
        id: 'e-point',
        title: 'Put the point first',
        rule: 'thesis',
        task: 'Rewrite this opening so the reader knows your main point in the first two sentences.',
        text: 'Throughout history, people have always had different opinions about many things, and technology is one of those things that people talk about a lot these days in many different ways.',
        hint: 'Write a sentence someone could disagree with. Then give one reason.',
        model: 'Schools should ban phones during class. Students who can’t check their phones remember more of what they learn, and they talk to each other again at lunch.',
      },
      {
        id: 'e-hedge',
        title: 'Cut the hedges',
        rule: 'weasel',
        task: 'Remove the weasel words and hedges. Name a source or state the claim plainly.',
        text: 'I think that maybe homework is not that useful. Some people say it causes stress, and many believe it does not really help younger students. In my opinion, schools should probably reconsider it.',
        hint: 'You wrote it, so the reader knows it’s what you think. Own the claim.',
        model: 'Homework does little for younger students. It adds stress to family evenings without improving test scores. Schools should drop it before age eleven.',
      },
      {
        id: 'e-evidence',
        title: 'Back it with an example',
        rule: 'evidence',
        task: 'Support the claim with a specific example, a number or a source.',
        text: 'Learning a second language is good for you. It helps in many ways and makes you better at lots of things in life.',
        hint: 'Start a sentence with “For example,” and give one concrete case.',
        model: 'Learning a second language pays off fast. For example, after six months of Spanish, I could order, haggle and get directions in Mexico City, and I spent 30% less than on my last trip because I wasn’t stuck in tourist restaurants.',
      },
      {
        id: 'e-long',
        title: 'Break up a long sentence',
        rule: 'long-sentences',
        task: 'Split this into two or three clear sentences.',
        text: 'Remote work has many benefits for employees, including the ability to avoid long commutes, which can save hours every week, as well as greater flexibility in scheduling, which allows people to take care of family responsibilities while still getting their work done on time.',
        hint: 'One idea per sentence. Look for “which” and “as well as”: they often hide a second sentence.',
        model: 'Remote work gives employees back their commute, often several hours a week. It also adds flexibility. People can pick up their kids at three and still finish their work on time.',
      },
    ],
    poetry: [
      {
        id: 'p-haiku',
        title: 'Count to 5-7-5',
        rule: 'syllables',
        framework: 'haiku',
        task: 'Fix the syllable counts so the haiku is exactly 5, 7 and 5. Hover a line to see its count.',
        text: 'the early morning rain\non the window of my small room\nI hear it fall',
        hint: 'Swap words for shorter or longer ones: “early morning rain” (6) → “morning rain” (4).',
        model: 'rain before sunrise\ntapping on my window glass\nthe kettle answers',
      },
      {
        id: 'p-concrete',
        title: 'Concrete, not abstract',
        rule: 'imagery',
        task: 'Replace every abstract word (love, pain, hope, heart) with something you could see, hear or touch.',
        text: 'My heart is full of love and pain\nand hope and sorrow and despair\nmy soul is lost in endless time',
        hint: 'What object holds this feeling? A cold mug, an empty chair, a voicemail you can’t delete.',
        model: 'Your coat still hangs behind the door.\nI keep the pockets as you left them:\na ticket stub, two coins, a button.',
      },
      {
        id: 'p-rhyme',
        title: 'Fix the limerick',
        rule: 'rhyme',
        framework: 'limerick',
        task: 'The last line should rhyme with lines 1 and 2 (AABBA). Rewrite it.',
        text: 'A cook with a passion for cheese\nWould sneak it in all of her teas.\nShe’d stir in some brie,\nThen sip it with glee,\nAnd her guests would all leave very quickly.',
        hint: 'Find a word that rhymes with “cheese” and “teas”, then build the punchline toward it.',
        model: 'A cook with a passion for cheese\nWould sneak it in all of her teas.\nShe’d stir in some brie,\nThen sip it with glee,\nWhile her guests fled as fast as they please.',
      },
      {
        id: 'p-endings',
        title: 'Strong line endings',
        rule: 'line-endings',
        framework: 'free',
        task: 'Re-break the lines so none ends on “the”, “of”, “and” or “a”.',
        text: 'I walked down to the\nedge of the water and\nwatched the light go out of\nthe sky over a\nharbor full of boats',
        hint: 'End each line on the word you want the reader to feel: a noun or a verb.',
        model: 'I walked down to the edge\nof the water and watched\nthe light go out of the sky\nover a harbor full of boats',
      },
    ],
    copy: [
      {
        id: 'k-headline',
        title: 'Write a real headline',
        rule: 'headline',
        task: 'Rewrite the headline in under 12 words with a clear benefit, a number or a “you”.',
        text: 'We are proud to announce the launch of our brand new rain jacket collection for the upcoming autumn season.',
        hint: 'What does the customer get? Lead with that.',
        model: 'Stay dry on your commute with a 9-ounce rain jacket.',
      },
      {
        id: 'k-you',
        title: 'Flip “we” to “you”',
        rule: 'you-vs-we',
        task: 'Rewrite so the customer is the subject of most sentences.',
        text: 'We are a family bakery. We bake our bread fresh every morning. We use local flour and we never add preservatives. We are open until 6 p.m.',
        hint: '“We bake fresh every morning” → “Your bread was baked this morning.”',
        model: 'Your bread was baked this morning, with flour from a farm 20 miles away. No preservatives, ever. Pick yours up any time before 6 p.m.',
      },
      {
        id: 'k-benefit',
        title: 'Features into benefits',
        rule: 'benefits',
        task: 'After each feature, add what it does for the customer.',
        text: 'The Volt blender has a 1,200-watt motor. It has six stainless steel blades. It comes with a travel cup. Buy it today.',
        hint: 'Add “so you can…” or “which means…” after every feature.',
        model: 'The Volt blender’s 1,200-watt motor crushes ice in 20 seconds, so you can make a smoothie before your coffee is ready. Blend straight into the travel cup, which means no extra dishes. Rinse it clean without taking it apart. Get yours today.',
      },
      {
        id: 'k-buzz',
        title: 'Cut the buzzwords',
        rule: 'buzzwords',
        task: 'Replace every buzzword with what the product actually does.',
        text: 'Our innovative, cutting-edge platform leverages seamless synergy to empower your team with robust, scalable solutions.',
        hint: 'Ask: what does a customer actually do with it on a Monday morning?',
        model: 'Plan your team’s week in one shared calendar. Everyone sees who’s busy, and nobody has to ask in Slack.',
      },
    ],
  };
})(window.WP = window.WP || {});
